### ISSUE TITLE
Add support for multiple installs

### ISSUE THREAD

**Issue by Atinux** [pi0/nuxt-config-schema#2]
Useful when having layers or module installing the module, until Nuxt supports skipping same modules install.

**Comment by Atinux** [comment]
Not needed: https://github.com/nuxt/nuxt.js/issues/9284#issuecomment-1257680329

**Comment by pi0** [comment]
Is the linked issue correct?

**Comment by Atinux** [comment]
Sorry it's that code: https://github.com/nuxt/framework/blob/main/packages/kit/src/module/define.ts#L40-L48
